server:
  port: 8080

spring:
  application:
    name: uni-db
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5431/postgres
    username: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
